name: Build & upload toolchain

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            clang \
            lld \
            llvm \
            gcc-12 \
            g++-12 \
            libstdc++-12-dev \
            libc6-dev \
            build-essential \
            python3 \
            ninja-build \
            cmake

      - name: Verify toolchain
        run: |
          g++-12 --version
          clang++ --version
          echo '#include <cstdint>
          uintptr_t x;' > test.cpp
          g++-12 test.cpp -c

      - name: Install project deps
        run: bash ci.sh deps

      - name: Build LLVM
        env:
          CC: gcc-12
          CXX: g++-12
        run: bash build-toolchain.sh

      - name: GitHub release
        run: bash ci.sh release
